apiVersion: v1
kind: Pod
metadata:
  name: http-echo-pod
spec:
  containers:
  - name: http-echo-container
    image: hashicorp/http-echo
    args:
      - "hello world"
    ports:
      - containerPort: 5678
