apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
      - name : nginx.config
      configmap:
      - name : nginx-config
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
          - containerPort: 80
        VolumeMounts:
          - name : nginx-volume
            mountPath: /usr/share/nginx/html
            readOnly: true
        resources: {}
status: {}
